### ISSUE TITLE
Day after Thanksgiving is a holiday in CA

### ISSUE THREAD

**Issue by s-heisler** [dr-prodigy/python-holidays#127]
Day after Thanksgiving is a holiday in CA: https://www.dmv.ca.gov/portal/dmv/detail/about/holidays

**Comment by s-heisler** [comment]
In fact, it appears to be one in a number of US states: https://www.officeholidays.com/countries/usa/black_friday.php

**Comment by dr-prodigy** [comment]
Hi, thank you.
Day after TG is already managed in the lib for a lot of US states (but, as you stated, not currently for CA). 
Unfortunately, in your links I can't find since when it's been holiday, and if it is going to remain like this in the future.
Would you please integrate your issue with these data? 
Thank you very much

**Comment by dr-prodigy** [comment]
Ping..
