### ISSUE TITLE
Confusion around Australian holidays

### ISSUE THREAD

**Issue by jameskirsop** [dr-prodigy/python-holidays#148]
In my particular use case, I'd like to show all the holidays for all states of Australia (referred to as provinces in this project) on a calendar, as we have staff working across the country. I know it's possible to add a number of Holiday base classes together, but we then lose the ability to know which holiday is for which state - especially since a holiday can have the same name but is held on a different date depending on the state.

Additionally, if I was to call the Australia class, my expectation would be to get all the national holidays and not additionally the ACT holidays. In my mind the default behaviour should be that we get given state/province specific holidays only when we need/request them.

To combat this, I'd suggest the following:
- When adding different holiday classes together, they are appended with information about the state/province each holiday is for (eg `Labour Day (ACT, NSW, SA)`)
- Dropping the default for countries provinces so that, like the US, a specific state can be requested when needed but otherwise only national holidays are returned by default

I'm happy to try and produce a PR that will achieve the first point - when I get a moment - if it's a direction the maintainers think would be useful.

**Comment by dr-prodigy** [comment]
Hi @jameskirsop ,
thank you very much for your contribution.

I surely can see your points, and they make good sense to me too.
What I feel important is to avoid / reduce at min any incompatibility with previous versions, but as long as your code is respectful about this (it seems quite so), I will for sure merge your PR.

NOTES
* I maybe wrong but, if I catch your idea well, it will take quite an extensive work to achieve point 1, due to how provincial holidays are appended to national ones (ie: only the selected prov holidays are considered, so the other ones are not available in any way at runtime).
* Point 2 changes lib's default behaviour a little (warn), but in a way which is surely preferable and more precise ( => ok), so I don't have any objections on it.

If you consider providing your work on these upgrades, please go on and I will be glad to release it.

Thank you very much again, cheers!

**Comment by dr-prodigy** [comment]
Closing this issue until a PR comes out .. thx ;-)
