### ISSUE TITLE
Czech -> Czechia or CzechRepublic

### ISSUE THREAD

**Issue by janpipek** [dr-prodigy/python-holidays#185]
Nice library!

However, I'd slightly change the name of class for Czech holidays. "Czech" is an adjective (like "Italian" or "Milanese"), not a country name. The short or the long name should be used instead.

Should I make a PR (perhaps with some deprecation warning)?

**Comment by dr-prodigy** [comment]
Hi Jan,
thank you very much!
I see your point.. It's not my fault, Czech implementation has been added in the past by another dev.. 
Anyway I agree we should better fix it. 

If you could contribute with your own PR, it would be great!
Some tips:
- for now, don't remove support for current name (Czech), just add a deprecation hint to it
- add a synonym for it (let's say czechia) 
- add tests for your new code, so that coveralls doesn't complain :) 
In a next release we will remove support for the misspelled name. 

Last but not least, start your work from "dev" branch, because I'll be merging your PR to it. 

Thanks a lot for your contribution, cheers! 
Dr. P

**Comment by janpipek** [comment]
Ok,

I'll follow the tips. However, there is no `dev` branch in your repository... Which one should I create the pull request against?

Jan

**Comment by dr-prodigy** [comment]
Hi Jan,
I made a mistake: I wrote "dev" branch, but I was meaning "beta".
Please work starting from it, thank you very much!
