### ISSUE TITLE
Holidays for Malta

### ISSUE THREAD

**Issue by SeanVella** [dr-prodigy/python-holidays#190]
Good morning :)

Can we get holidays for Malta please?

**Comment by dr-prodigy** [comment]
Good morning!
Unfortunately, this ain't no restaurant, so no orders accepted, sorry :-)

In order to have your request satisfied, I would suggest you to provide your preferred degree of contribution to the project (holidays information / code implementation / unit tests): the more contribution you provide, the more likely to see the work done in a short time.

Best regards, have a nice day!
