### ISSUE TITLE
Passing a year to .get and .get_list yields only New Year's Day

### ISSUE THREAD

**Issue by thoha** [dr-prodigy/python-holidays#198]
If I try pass a year to .get or .get_list, only New Year's Day is returned. I would expect to get a list of all the holidays in that year.

To expand, I am using the CountryHoliday class, but don't know the exact dates of the holidays, so would like to retrieve them by passing the year.

**Comment by dr-prodigy** [comment]
Hi,
you haven't provided any code in your issue, but anyway, it seems, being using the year only, you're implicitly passing a single date (i.e.: ????/1/1) to the method, so that's why you receive only New Year's Day.

You should instead be using a date range, like this ( = [https://github.com/dr-prodigy/python-holidays#example-usage](url) 's last snippet ):
```
>>> from datetime import date
>>> holidays.US()[date(2013, 12, 31): date(2014, 1, 2)]
```

Cheers
dr-p
