### ISSUE TITLE
Issue with Czech

### ISSUE THREAD

**Issue by cjpit** [dr-prodigy/python-holidays#210]
```
>>> hols = holidays.CountryHoliday('CZ')
>>> hols = holidays.CountryHoliday('Czech')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/holidays.py", line 233, in CountryHoliday
    country_holiday = globals()[country](prov=prov, state=state)
TypeError: __init__() got an unexpected keyword argument 'prov'
```

**Comment by redy007** [comment]
Hey, I am using:

`cz_holidays = holidays.CZ()`

It works.

**Comment by cjpit** [comment]
CZ works, 'Czech' doesnt... Thats what I'm showing above...'Czech' is mentioned in the docs as it should be able to be used.

**Comment by dr-prodigy** [comment]
Sorry you are right.. That's because:
- "Czech" has been deprecated. The currently correct keyword is "Czechia"
`class Czech(Czechia):
    def __init__(self):
        warnings.warn("Czech is deprecated, use Czechia instead.",
                      DeprecationWarning)
        super(Czech, self).__init__()
`
so I need to update the doc accordingly. I'll do it, thx 
- there's an issue when deprecation happens during `holidays.CountryHoliday('XXX')` call. Should dive into it and fix it
Thank you very much, pls let me know how it goes

**Comment by dr-prodigy** [comment]
Just pushed a fix for those issues.. thanks again 👍

**Comment by dr-prodigy** [comment]
No complaints => all OK.. closing ;-)
