### ISSUE TITLE
FR instead of FRA for France

### ISSUE THREAD

**Issue by redy007** [dr-prodigy/python-holidays#211]
Hi there,

I am using CountryField within your project. Everything works great, but France. I know you wrote in the code: "FR already exists (Friday), we don't want to mess it up".

I changed it locally and all works (as it should). Don't you want to consider change your mind on this and change the class to 'FR' instead of 'FRA'?

**Comment by dr-prodigy** [comment]
Hi,
I don't think it would be a great idea: code would get less robust, and we would go to break compatibility with previous versions.
Why would you expect to have FR instead of FRA? France support has been like that since the initial implementation, and there are a number of other managed states named with 3 letters instead of 2..

Please let me know, thank you
dr-p

**Comment by dr-prodigy** [comment]
Okay, time to close this.. cheers
