### ISSUE TITLE
UAE Holidays

### ISSUE THREAD

**Issue by newillusions** [dr-prodigy/python-holidays#265]
Any chance of adding the UAE holidays?
Even just the fixed date ones would be ok.

**Comment by rpanai** [comment]
@newillusions I suggest you to have a look at the code and try to fix and make a PR. Otherwhise it will be great if you could make list of wrong holidays.

**Comment by dr-prodigy** [comment]
Hi @rpanai thank you.
Just a short clarification : in this case we are not talking about fixes on wrong holidays, but instead support for a new country (United Arab Emirates), not currently available in the library.
This task is not easy due to specific regulations / language - cultural differences, that's why a help for it is desirable. 
Thanks, best
dr-p

**Comment by mborsetti** [comment]
@newillusions do you have an authoritative source (law, ministry, or similar) for the holidays?
