### ISSUE TITLE
Add Romania holidays

### ISSUE THREAD

**Issue by rvencu** [dr-prodigy/python-holidays#337]
Month | Day | Name | Comment
-- | -- | -- | --
1 | 1 | Anul Nou |  
1 | 2 | Anul Nou |  
1 | 24 | Ziua Unirii   Principatelor Romane |  
4 | 17 | Vinerea Mare | Use orthodox Easter calculator here for the Friday before Easter
4 | 19 | Paste Ortodox | Use orthodox Easter calculator here for first day of Easter
4 | 20 | Paste Ortodox | Use orthodox Easter calculator here for second day of Easter
5 | 1 | Ziua Muncii |  
6 | 1 | Ziua Copilului |  
6 | 7 | Rusalii | Use orthodox Easter calculator here for first day of Orthodox Pentecost
6 | 8 | Rusalii | Use orthodox Easter calculator here for second day of Orthodox Pentecost
8 | 15 | Adormirea   Maicii Domnului |  
11 | 30 | Sfantul Andrei |  
12 | 1 | Ziua Nationala   a Romaniei |  
12 | 25 | Craciunul |  
12 | 26 | Craciunul |

**Comment by rvencu** [comment]
I prepared romania.py file as well (easy adaptation from Greece to overcome calculated dates).
[romania.zip](https://github.com/dr-prodigy/python-holidays/files/4900747/romania.zip)

**Comment by rvencu** [comment]
Please also update the Splunk App accordingly. Thanks.

**Comment by dr-prodigy** [comment]
Hi,
thank you for your interest and support in python_holidays.
I have to point out that, although very appreciated, your work is not needed anymore, since I've just merged the support for Romania a few days ago, as proposed in a PR by dorianm (pls check beta branch).

If you still would like to help, I would then suggest you to double-check its correctness (although I'm pretty sure it's a very good job), and in case, apply fixes / improvements. Would you?

PS: I don't know nor have any control on "Splunk App", sorry!

Thanks, best regards
dr-p

**Comment by rvencu** [comment]
Thanks, I will review as proposed, did not notice the beta branch update :)

**Comment by rvencu** [comment]
I can confirm, the beta implementation is better than my own work. Thanks

**Comment by dr-prodigy** [comment]
Okay! Closing this, thank you very much :-)
Cheers
dr-p
