### ISSUE TITLE
Appearance of the object is that it's an empty dict, with a custom repr that would be solved

### ISSUE THREAD

**Issue by kootenpv** [dr-prodigy/python-holidays#360]
If you want I could make a PR that would look like the following:

```python
>>> import holidays
>>> us_holidays = holidays.UnitedStates()
>>> us_holidays
holidays.UnitedStates(country="US", prov=None, state=None)
```

Wouldn't this be nice? Let me know if I should make the PR

**Comment by dr-prodigy** [comment]
Hi @kootenpv 
thank you for your interest in python-holidays.
Being sincere, even if I consider this nice as somehow / sometimes useful, on the other hand it would impact on the current library behaviour, so due to the wide usage of it, I don't think we can release it as you suggest.
If you think of a different interface to access the current initialization state (possibly regarding the loaded years too), it would surely be very appreciated / merged.
Thanks again, cheers !

**Comment by d33tah** [comment]
Hi @dr-prodigy! Thanks for this awesome library! I recently found it while looking for a solution to an ugly banking-related problem and I appreciate having an elegant solution to it.

I'd like you to reopen the issue, because I agree with @kootenpv's point. Here's why:

I found this library looking for a list of holidays in Poland. I didn't expect it to work, but got intrigued by hundreds of Github stars so I tried it out. So I flick through the README, `pip install it`, import it and try it out in my own way:

```
>>> import holidays
>>> holidays.Poland()
{}
```

So... an empty dictionary? "That's not a way to tell me that Poland isn't supported!" - I thought. So I looked at the README again, saw that Poland was marked as "None" and almost moved along, assuming it's just yet another popular Python library that doesn't seem to work. Curious why it's the case though, I looked at the code and found that it seems to make sense. So I tried another approach:

```
>>> d = {}
>>> import holidays
>>> holidays.Poland._populate(d, 2021)
>>> d
{datetime.date(2021, 1, 1): 'Nowy Rok', datetime.date(2021, 1, 6): 'Święto Trzech Króli', datetime.date(2021, 4, 4): 'Niedziela Wielkanocna', datetime.date(2021, 4, 5): 'Poniedziałek Wielkanocny', datetime.date(2021, 5, 1): 'Święto Państwowe', datetime.date(2021, 5, 3): 'Święto Narodowe Trzeciego Maja', datetime.date(2021, 5, 23): 'Zielone Świątki', datetime.date(2021, 6, 3): 'Dzień Bożego Ciała', datetime.date(2021, 8, 15): 'Wniebowzięcie Najświętszej Marii Panny', datetime.date(2021, 11, 1): 'Uroczystość Wszystkich świętych', datetime.date(2021, 11, 11): 'Narodowe Święto Niepodległości', datetime.date(2021, 12, 25): 'Boże Narodzenie (pierwszy dzień)', datetime.date(2021, 12, 26): 'Boże Narodzenie (drugi dzień)'}
```

Yay! Maybe I can use it after all then! You're probably shaking your head in disagreement... rightfully so, because I'm supposed to do something like `datetime.date(2021, 1,1) in holidays.Poland()`. To which I'd normally reply "but what's the point checking if I already got an empty dict...?"

So that's basically the problem. The __repr__ is misleading and should be changed. Because right now if you come with a lesser known country such as Poland, you're kind of used to libraries not working and you might just move along, kind of agreeing with that assumed neglect.

Here are solutions I propose:

* like @kootenpv suggested, make __repr__ actually return a string that doesn't suggest it's a plain dict,
* if you assume people rely on this behavior of __repr__ (which they probably shouldn't) and you want to be nice to them, throw a DeprecationWarning that this __repr__ is deprecated and you'd rather say it's an instance of holidays.countries.poland.Poland or something,
* explicitly show in README that this {} is misleading and __contains__ is overloaded. Showing it in an interactive example is better than writing it as a part of text as some folks scan through dozens of libraries and might just omit something that doesn't seem to work.

**Comment by dr-prodigy** [comment]
Hi @d33tah
first of all thank you for your interest and time spent in explaining your point.

Although:
- the doc provides [Available Countries](https://github.com/dr-prodigy/python-holidays#available-countries) paragraph.. why in the world we should list unimplemented countries there? :-)
- [Examples](https://github.com/dr-prodigy/python-holidays#example-usage) paragraph starts with 4 rows of code explaining how to use the sw.. why not giving them a quick glance before blaming the sw for not working, and/or tinkering with the internals of the lib? :-)

I must admit anyway that the library, even being smart and convenient in its usage, isn't self-explanatory.
On a second thought, I came to the decision of reviewing both `__repr__` and `__str__` methods to return clearer / more useful information.
In order to preserve debug-friendliness, the reviewed values will be return only on uninitialized state, while for initialized objects the usual list of holiday dates will be returned.

I will soon release a fix for this, thank you again 👍

**Comment by dr-prodigy** [comment]
Done and pushed on beta.. cheers 👍

**Comment by dr-prodigy** [comment]
Ps: I was forgetting.. @d33tah please let me know your thoughts, thanks!

**Comment by d33tah** [comment]
@dr-prodigy yup! That seems to solve the problem :) And once again, thanks for implementing this library!

**Comment by dr-prodigy** [comment]
Yay! :-)
And if you wish, I would really appreciate you collaborating to improve Poland holidays, or anything else in the lib.. we always need passionate and experienced coders to improve python-holidays!
Thanks a lot again, cheers! 👍 
dr-p

**Comment by d33tah** [comment]
@dr-prodigy I took a quick look at the Polish code, it seems to look fine. If there was any potential problem, I'd be looking for it in those two lines:

```
        self[e + rd(days=49)] = "Zielone Świątki"
        self[e + rd(days=60)] = "Dzień Bożego Ciała"
```

According to Polish Wiki, Zielone Świątki should always be on Sunday and Dzień Bożego Ciała on Thursday. Might be worth checking if that's actually the case during the coming and previous years.

There are also some historical dates not implemented, but I'm not sure how important it is to be able to reliably date back to before 1989.
