### ISSUE TITLE
Chinese holidays?

### ISSUE THREAD

**Issue by faouziamrouche** [dr-prodigy/python-holidays#361]
Is there a script for Chinese holidays in this library? If not, is there a reason why? as it's one of the biggest economies and thus this data is quite relevant in many fields.

**Comment by mborsetti** [comment]
It's open source.  You're welcome to contribute it, and thanks in advance!

**Comment by dr-prodigy** [comment]
Hi,
thanks for your interest in this project.
In fact, Chinese holidays, due to their peculiar language/alphabet and regulations, are clearly a pretty complex task.
Therefore (and due to lack of contributors) there's not been space for its development until now.
As already stated any contribution is welcome, thx!
dr-p

**Comment by ai-xcode** [comment]
I'm a Chinese,I want to help complete this work。Can you give me some information and tell me where to start。

**Comment by PMLP-novo** [comment]
@HomeIntelligentCube if you can help discribe logic that is needed in order to determine if a given day is a holiday in China then it could be perfect. Alternatively take a look at the country files in https://github.com/dr-prodigy/python-holidays/tree/master/holidays/countries for how logic is coded up for different countries.

**Comment by PMLP-novo** [comment]
I found the following holiday package for javascript, which has Chinesse holidays: https://github.com/commenthol/date-holidays/blob/master/data/countries/CN.yaml which could be an inspiration.

**Comment by tserekh** [comment]
I have a pull requiest on this issue https://github.com/dr-prodigy/python-holidays/pull/515

**Comment by dr-prodigy** [comment]
@tserekh hi, your PR is now merged in beta.. thank you very much for your support! 👍
