### ISSUE TITLE
NYSE Holidays

### ISSUE THREAD

**Issue by Z223I** [dr-prodigy/python-holidays#458]
I wish to add holidays for the NYSE.  Should I refer to it as a Country, Providence, or State.  I wish to also do NASDAQ.

The NYSE and NASDAQ both have early close days like the day after US Thanksgiving.  How would you suggest I do that?

Thanks in advance!

Z223I

**Comment by mborsetti** [comment]
> I wish to add holidays for the NYSE. Should I refer to it as a Country, Providence, or State. I wish to also do NASDAQ.

@Z223I thanks for the contribution!! dr-prodigy will give the definitive answer here, but below are my suggestions.

@dr-prodigy to keep with ISO standardization, I _suggest_ we use ISO 10383 (the standard which "specifies a universal method of identifying exchanges, trading platforms and regulated or non-regulated markets as sources of prices and related information in order to facilitate automated processing"). These codes are at https://www.iso20022.org/market-identifier-codes.

Maybe we create a pseudo-country called "MIC" (for Market Identifier Code) and use the ISO 10383 _operating_ MIC as the identifier, so that it would look like this:

`nyse_holidays = holidays.MIC('XNYS')`
`nasdaq_holidays = holidays.MIC('XNAS')`

Alternatively we can keep the market within the country it belongs to (as listed in ISO 10383), hoping that there is no collision with a ISO 3166-2 subdivision code (see #374), so that it would look like this:

`nyse_holidays = holidays.US('XNYS')`
`nasdaq_holidays = holidays.US('XNAS')`

Personally, I prefer option 1, not only because there's no risk of collisions, but also because it's one less implementation step for anyone using this package (i.e. all they need is the MIC, they don't have to keep track, or look up, where that exchange is located; plus markets, which are mostly electronic anyway, may relocate to a different country, e.g. post-Brexit or whatever, creating maintenance and implementation headaches).

> The NYSE and NASDAQ both have early close days like the day after US Thanksgiving. How would you suggest I do that?

Ugh. @dr-prodigy any ideas?  That's actually really useful information!

**Comment by Z223I** [comment]
@mborsetti That info looks really good.  I will wait for @dr-prodigy to also respond.

Thanks!!

Z223I

**Comment by Z223I** [comment]
Maybe the short market days can be handled like "Holiday Observed".  I need to dive into your code.

**Comment by Z223I** [comment]
@dr-prodigy I went with option 1.  Inherited from Holidays so it may be easily used for any country.

For "Short Trading Days", I put it in the name just like "Observed."

Now I will write some tests.

Thanks again,

Z223I

**Comment by dr-prodigy** [comment]
Hey there sorry, I've been off for quite a long time.. more and more difficult to find time for python-holidays!

First of all, thank you both.. I really like this initiative, and I agree with you: option 1 seems definitely the best to me too.

I opened a new beta course today.. I'll be waiting for your work @Z223I !

Thx again, cheers everyone!
dr-p

**Comment by JustinKurland** [comment]
Any updates on this I think this would be a fantastic addition to an already incredibly useful package!

**Comment by mborsetti** [comment]
@JustinKurland 

> Any updates on this I think this would be a fantastic addition to an already incredibly useful package!

It follows, then, that a contribution would therefore be extremely fantastic!  

Do you have some spare time to contribute?

**Comment by JustinKurland** [comment]
@mborsetti I would love to help contribute, and will do, but at this precise moment I am particularly swamped. Will check in with a friend who has implemented something similar in an R package he developed and circle back to try and assist on this very thing. 🙌🏻

**Comment by dr-prodigy** [comment]
Just released in beta thru #651 . Closing this, thanks! 👍
