### ISSUE TITLE
England has different holidays to Scotland, NI and Wales yet can only select UK as a whole

### ISSUE THREAD

**Issue by thefunkygibbon** [dr-prodigy/python-holidays#566]
one of my routines which i set up to use holidays didn't work today as it is a national holiday in scotland (but not in england where i am). 

there doesn't appear to be a way of specifically stating these countries.   Yet there are a way to specifically state US states etc for them to use their specific holiday dates. 

Any chance UK can be split out in the same way?

**Comment by thefunkygibbon** [comment]
looked at the code and saw England as a usable variable.  Seems to be ok.  
nothing to see here (but might be a better idea to make it obvious in the table of countries in the readme)

**Comment by dr-prodigy** [comment]
Great @thefunkygibbon, thanks!
We should in fact consider a possible refactoring, being UK a pretty unique case in python-holidays (being each region a de-facto standalone country derived from the UK main class, instead of a state inside UK class as for the other countries, including US).

Being that a breaking change, anyway, it will take some extra-cares to add it (eg: deprecation in a release -> removal in a further release).. but we will do it, when possible.

Thanks, meanwhile! 👍

**Comment by thefunkygibbon** [comment]
I don't know that it does need to change really.. using "England" instead of "UK" works properly and as presumably designed. 

If you could maybe just add it to the documentation so it's a little easier to work out that using the full country name works for those specific countries .

The UK is an awkward beast.
