### ISSUE TITLE
AU VIC Next Holiday shown incorrectly

### ISSUE THREAD

**Issue by kaizersoje** [dr-prodigy/python-holidays#610]
The next holiday for VIC, Australia is showing up as Good Friday (15/4/22). However, the next holiday should be Labour Day (14/3/22). The labour day holiday is shown in the holiday list but not in the right order. It shown in between Queen's Birthday (Jun) and Grand Final Day (Sep).

![image](https://user-images.githubusercontent.com/54566217/151699436-6fc63b0b-0183-4028-8184-dfb343a0184e.png)

**Comment by mborsetti** [comment]
@kaizersoje This library, in order to be as efficient as possible, does not sort the output by date.

@dr-prodigy Maurizio, funny to see this issue being opened because as I was working on my contribution this weekend I bumped into this as well, and wondered why the holidays aren't returned sorted. It somehow was my expectation too that they would be, but then remembered the required and welcomed focus on speed. I can do a PR to add warnings and examples in the docs about this.

We could also add a `sorted` parameter, default it to False, and do the sorting in the library if set to True. Can add this to my PR.

What do you think?

**Comment by kaizersoje** [comment]
@mborsetti Due to dates not being sorted, the state to the next holiday is also incorrect.
