### ISSUE TITLE
12 July 2017 is a holiday in UK

### ISSUE THREAD

**Issue by thefuckinggasvols** [dr-prodigy/python-holidays#63]
Why is today holiday in uk?

```
if datetime.date.today() in holidays.UK():
        print('UK holiday')
```

**Comment by oiffrig** [comment]
```python
>>> holidays.UK()[datetime.date.today()]
'Battle of the Boyne [Northern Ireland]'
```
However, it seems to concern only Northern Ireland.

**Comment by thefuckinggasvols** [comment]
Thanks for the explanation. Is there a "UK Bank Holiday" equivalent?

**Comment by hugovk** [comment]
There's quite a few which are only for Northern Ireland or Scotland. I think all the England and Wales ones are also holidays in NI and Scotland.

https://www.gov.uk/bank-holidays

Perhaps the home nations should be added for the UK as "Provinces/States Available"?

https://github.com/ryanss/python-holidays#available-countries

**Comment by dr-prodigy** [comment]
From the code, it seems like that by design. Not really sure if it's correct or not anyway!

**Comment by coder6464** [comment]
Use holidays.England() for UK Bank Holidays.  I've checked this against https://www.gov.uk/bank-holidays

**Comment by hugovk** [comment]
This is a bug. 

This particular holiday should only be in `holidays.NorthernIreland()`.

**Comment by hugovk** [comment]
Or rather, this is by design.

>>> import holidays
>>> for date, name in sorted(holidays.UK(years=2018).items()):
...     print(date, name)
...
2018-01-01 New Year's Day
2018-01-02 New Year Holiday [Scotland]
2018-03-30 Good Friday
2018-04-02 Easter Monday [England, Wales, Northern Ireland]
2018-05-07 May Day
2018-05-28 Spring Bank Holiday
2018-08-06 Summer Bank Holiday [Scotland]
2018-08-27 Late Summer Bank Holiday [England, Wales, Northern Ireland]
2018-11-30 St. Andrew's Day [Scotland]
2018-12-25 Christmas Day
2018-12-26 Boxing Day
>>>

See https://github.com/dr-prodigy/python-holidays/issues/40 for details.

If the holiday has square brackets, you'll need to check the country you're interested in is mentioned.

Or you can check `holidays.England()` or whichever ones you're interested in.

**Comment by hugovk** [comment]
Well, at the moment it is working as designed, as detailed in #40.

If that's fine for everyone then this can be closed.

**Comment by dr-prodigy** [comment]
Okay, that's what I wanted to hear.. ;)
Thx mate!
