### ISSUE TITLE
TypeError: Cannot convert type '<class 'pandas.core.series.Series'>' to date.

### ISSUE THREAD

**Issue by celestinoxp** [dr-prodigy/python-holidays#643]
Hi, i have problem. 
Idea: create a boolean dataframe with hollidays... example: data['feriado'], true or false, but i need get a date from data['data'].

i try:

data['feriado'] = data['data'] in pt_holidays

but have error:
TypeError: Cannot convert type '<class 'pandas.core.series.Series'>' to date.

Note: data['data'] is 2022-03-16....

and i can´t convert. i try 1 million different ways but always have error to convert

i think you should consider convert series automatically to date

for example:

data['feriado'] = data['data'] in pt_holidays

i only want a boolean result like data['feriado'] = true/false

**Comment by dr-prodigy** [comment]
Unfortunately, holidays' `HolidayBase` object is by design a `Dict[date, str]`, so it won't support inclusion evaluations based on different / specific data types such as pandas Series.
Therefore, in order to obtain the correct result, you will have to `convert data['data']` into a `datetime.date` object.
