### ISSUE TITLE
Canadian Holidays are not working in 2022

### ISSUE THREAD

**Issue by Dpananos** [dr-prodigy/python-holidays#697]
The folllowling should return "Christmas Day" but does not

```
import holidays
holidays.CA().get('2022-12-25')
# No return
```

However, it does work for the US

```
holidays.US().get('2022-12-25')
'Christmas Day'
```

**Comment by kasya** [comment]
I'll look into this.

**Comment by dr-prodigy** [comment]
Hi @Dpananos 
I made a check, and I confirm Canada code is working as expected: the difference between it and the other countries is it applies observance by default:
```
>>> import holidays
>>> h = holidays.CA()
>>> h
holidays.country_holidays('CA', subdiv='ON')
>>> h.get('2022-12-25')
>>> h
{datetime.date(2022, 1, 1): "New Year's Day", datetime.date(2022, 2, 21): 'Family Day', datetime.date(2022, 4, 15): 'Good Friday', datetime.date(2022, 4, 18): 'Easter Monday', datetime.date(2022, 5, 23): 'Victoria Day', datetime.date(2022, 7, 1): 'Canada Day', datetime.date(2022, 8, 1): 'Civic Holiday', datetime.date(2022, 9, 5): 'Labour Day', datetime.date(2022, 10, 10): 'Thanksgiving', datetime.date(2022, 12, 27): 'Christmas Day (Observed)', datetime.date(2022, 12, 26): 'Boxing Day'}
```
Basically, Christmas Day is there, but for 2022, is shifted to 2022-12-27.

In the end, this behaviour could be debated (could you please check whether it's correct or not?), but there seems no to be any technical issue behind it (ie: it's like so by design).

Please let me know if this makes sense to you, thank you

**Comment by bkthomps** [comment]
Here's a fix: https://github.com/dr-prodigy/python-holidays/pull/715

**Comment by dr-prodigy** [comment]
This is to be closed.. thx!

**Comment by tzhouML** [comment]
@dr-prodigy 

I am calling the exact same 2022 holidays today and I'm getting a completely different result:

`dict_items([(datetime.date(2024, 1, 1), "New Year's Day"), (datetime.date(2024, 3, 29), 'Good Friday'), (datetime.date(2024, 7, 1), 'Canada Day'), (datetime.date(2024, 9, 2), 'Labour Day'), (datetime.date(2024, 12, 25), 'Christmas Day'), (datetime.date(2024, 2, 19), 'Family Day'), (datetime.date(2024, 5, 20), 'Victoria Day'), (datetime.date(2024, 10, 14), 'Thanksgiving Day'), (datetime.date(2024, 12, 26), 'Boxing Day')])`

note that a lot of holidays are missing like Victoria day, Civic Holiday etc. Can you help me understand what happened that canadian holidays are now missing like this?

**Comment by arkid15r** [comment]
> @dr-prodigy
> 
> I am calling the exact same 2022 holidays today and I'm getting a completely different result:
> 
> `dict_items([(datetime.date(2024, 1, 1), "New Year's Day"), (datetime.date(2024, 3, 29), 'Good Friday'), (datetime.date(2024, 7, 1), 'Canada Day'), (datetime.date(2024, 9, 2), 'Labour Day'), (datetime.date(2024, 12, 25), 'Christmas Day'), (datetime.date(2024, 2, 19), 'Family Day'), (datetime.date(2024, 5, 20), 'Victoria Day'), (datetime.date(2024, 10, 14), 'Thanksgiving Day'), (datetime.date(2024, 12, 26), 'Boxing Day')])`
> 
> note that a lot of holidays are missing like Easter Monday, Civic Holiday etc. Can you help me understand what happened that canadian holidays are now missing like this?

It doesn't seem the issue is related to this thread. It's always a good idea to create a new issue instead of posting to a one closed 2 years ago.

If you look at the documentation you'll find how to use entity [supported category holidays](https://python-holidays.readthedocs.io/en/latest/examples.html#holiday-categories-support) -- it seems you need GOVERNMENT one.

Please also note @dr-prodigy no longer maintains this package.
